# syntax=docker/dockerfile:experimental
FROM mrhuangyuhui/gitbook

ARG registry

WORKDIR /book

COPY . /book

RUN --mount=type=cache,target=/book/node_modules \
    --mount=type=cache,target=/root/.npm \
    npm config set registry $registry -g \
    && gitbook install
